spring:
  application:
    name: item-validator
    version: 1.0.0
    description: Item Validator Service
  sleuth:
    enabled: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
